mdw_demo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MDWDemoBundle:Default:index }

articulos: 
  pattern: /articulos
  defaults: { _controller: MDWDemoBundle:Default:articulos}
  
articulo:
  pattern: /articulo/{id}
  defaults: { _controller: MDWDemoBundle:Default:articulo}
  requirements:
    id: \d+
  
hello:
  pattern:  /hello
  defaults: { _controller: MDWDemoBundle:Default:hello }

articulo_listar:
  pattern: /articulos/listar
  defaults: { _controller: MDWDemoBundle:Articulos:listar }

articulo_crear:
  pattern: /articulos/crear
  defaults: { _controller: MDWDemoBundle:Articulos:crear }

articulo_editar:
  pattern: /articulos/editar/{id}
  defaults: { _controller: MDWDemoBundle:Articulos:editar }
  
articulo_visualizar:
  pattern: /articulos/visualizar/{id}
  defaults: { _controller: MDWDemoBundle:Articulos:visualizar }

articulo_borrar:
  pattern: /articulos/borrar/{id}
  defaults: { _controller: MDWDemoBundle:Articulos:borrar }
  
articulo_new:
  pattern: /articulo/new
  defaults: { _controller: MDWDemoBundle:Articulos:new}
  
ver_articulos:
  pattern: /ver-articulos
  defaults: { _controller: MDWDemoBundle:Articulos:verArticulos }

MDWDemoBundle_noticias:
    pattern:  /noticias
    defaults: { _controller: MDWDemoBundle:Notice:index }

MDWDemoBundle_noticeView:
    pattern:  /leerNoticia/{notice_id}
    defaults: { _controller: MDWDemoBundle:Notice:noticeView }

